### ISSUE TITLE
vcloud-edge-configure does not appear to accept a numeric port number

### ISSUE THREAD

**Issue by davehatton** [gds-operations/vcloud-edge_gateway#127]
Using the input

```
 - :id: 3
    :enabled: true
    :match_on_translate: false
    :description: '10.113>10.111'
    :policy: allow
    :protocols: any
    :source_ip: 10.113.0.0/16
    :source_port_range: 'Any'
    :destination_ip: 10.111.0.0/16
    :destination_port_range: '80'
    :enable_logging: true
```

with vcloud-edge-configure gives the following error

```
status: error, error: {:minorErrorCode=>"NETWORK_INTERNAL_SERVER", :message=>"Unable to perform this action. Contact your cloud administrator.", :majorErrorCode=>"500"}
/usr/local/share/gems/gems/fog-1.29.0/lib/fog/vcloud_director/compute.rb:435:in `wait_and_raise_unless_success': status: error, error: {:minorErrorCode=>"NETWORK_INTERNAL_SERVER", :message=>"Unable to perform this action. Contact your cloud administrator.", :majorErrorCode=>"500"} (Fog::Compute::VcloudDirector::TaskError)
        from /usr/local/share/gems/gems/fog-1.29.0/lib/fog/vcloud_director/compute.rb:424:in `process_task'
        from /usr/local/share/gems/gems/vcloud-core-1.0.2/lib/vcloud/core/fog/service_interface.rb:177:in `post_configure_edge_gateway_services'
        from /usr/local/share/gems/gems/vcloud-core-1.0.2/lib/vcloud/core/edge_gateway.rb:39:in `update_configuration'
        from /usr/local/share/gems/gems/vcloud-edge_gateway-1.5.0/lib/vcloud/edge_gateway/configure.rb:25:in `update'
        from /usr/local/share/gems/gems/vcloud-edge_gateway-1.5.0/lib/vcloud/edge_gateway/cli.rb:34:in `run'
        from /usr/local/share/gems/gems/vcloud-edge_gateway-1.5.0/bin/vcloud-edge-configure:5:in `<top (required)>'
        from /usr/local/bin/vcloud-edge-configure:23:in `load'
        from /usr/local/bin/vcloud-edge-configure:23:in `<main>'
```

Using 'Any' rather that '80' works. Am I doing something wrong?

**Comment by mattbostock** [comment]
@davehatton: Sorry for the delay in replying to you. I can't see any obvious problem; I would suggest raising this with your vCloud Director provider.
